spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      additional-exclude: database/*
      
  jpa:
    open-in-view: false
    properties: 
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        '[use_sql_comments]': true
        '[highlight_sql]': true
        '[jdbc.time_zone]': Asia/Ho_Chi_Minh
        '[connection.pool_size]': 10
        '[connection.autocommit]': true
        '[hbm2ddl.auto]': 'none'
  datasource:
    db1:
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      encoding: UTF-8
    #datasource 2
#    db2:
#      url: jdbc:sqlite:src/main/resources/database/mydb.sqlite3
#      driver-class-name: org.sqlite.JDBC

init-data:
  admin:
    email: ${EMAIL_ADMIN}
    password: ${PASSWORD_ADMIN}
    sdt: ${ SDT_ADMIN }
  token:
    secret-key-access: ${SECRET_KEY_ACCESS}
    secret-key-refresh: ${SECRET_KEY_REFRESH}
    expire-date: 6
    issuer: dacn.com
  token-refresh:
    expire-date: 36

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: dacn-backend
    version: 1.0.0
    url: http://localhost:8080
    title: Dự án cá nhân của Quân

logging:
  level:
    '[com.zaxxer.hikari.HikariConfig]': DEBUG


